import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Welcome from "@/components/Welcome";
import User from "@/components/User";
import Description from "@/components/Description";
import Pet from "@/components/Pet";

export default function Home() {
  return (
    //Fragment: Envolve as tags que contém o conteúdo do site, elemento pai que envolve todas as outras tags
    //É possível usar uma <div> no lugar do Fragment
    <> 
      {/* head é um elemento padrão do React */}
      <Head> 
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
      <h1>Hello World! Meu primeiro Site em React!</h1>
      {/* Importando o componente */}
      <Welcome/>
      <User/>
      {/* Importando e enviando propriedades (props) para o componente Description*/}
      <Description city="Registro" age={18} email="erlon@email.com"/>
      {/* Componente com a desestruturação de props */}
      <Pet name="Rex" breed="PitBull" age={3}/>
     </main>
     
    </>
  );
}
